# Generated by Django 5.0.6 on 2024-07-10 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companion', '0004_alter_companion_price_per_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('on_progress', 'Sedang Berjalan'), ('completed', 'Order Selesai')], default='pending', max_length=12)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companion.companion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
