# Generated by Django 5.0.6 on 2024-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('on_progress', 'Sedang Berjalan'), ('completed', 'Order Selesai')], default='pending', max_length=12),
        ),
    ]
