# Generated by Django 5.0.6 on 2024-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_companion_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='price_per_hour',
            field=models.IntegerField(),
        ),
    ]
