# Generated by Django 5.0.6 on 2024-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0003_alter_companion_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
