# Generated by Django 4.2.2 on 2024-06-27 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('id_card', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('bank_account', models.CharField(blank=True, choices=[('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('BRI', 'BRI'), ('Mega', 'Mega'), ('BSI', 'BSI'), ('CIMB', 'CIMB')], max_length=50, null=True)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('services_offered', models.JSONField()),
                ('instagram_account', models.CharField(blank=True, max_length=255, null=True)),
                ('hourly_rate', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Wanita', 'Wanita')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_companion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='CompanionGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companion_images/')),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='users.companion')),
            ],
        ),
        migrations.AddField(
            model_name='companion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
