# Generated by Django 4.2.2 on 2024-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companion_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='hourly_rate',
        ),
    ]
