# Generated by Django 4.2.2 on 2024-06-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companion_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='bank_account',
            field=models.CharField(choices=[('BCA', 'BCA'), ('Mandiri', 'Mandiri'), ('BRI', 'BRI'), ('Mega', 'Mega'), ('BSI', 'BSI'), ('CIMB', 'CIMB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companion',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companion',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companion',
            name='images',
            field=models.ImageField(upload_to='companion_images/'),
        ),
        migrations.AlterField(
            model_name='companion',
            name='instagram_account',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companion',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companion',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
