# Generated by Django 4.2.2 on 2024-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_companion',
            field=models.BooleanField(default=False),
        ),
    ]
