# Generated by Django 4.2.2 on 2024-06-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review_companiongallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
