# Generated by Django 4.2.2 on 2024-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_companion_services_offered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='companion',
            name='services_offered',
            field=models.JSONField(default=True, null=True),
        ),
    ]
