# Generated by Django 4.2.2 on 2024-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
