# Generated by Django 4.2.2 on 2024-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_companion_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='services_offered',
            field=models.JSONField(),
        ),
    ]
