# Generated by Django 4.2.2 on 2024-06-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='hourly_rate',
            field=models.IntegerField(),
        ),
    ]
