# Generated by Django 4.2.2 on 2024-06-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_companion_services_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='images',
        ),
        migrations.RemoveField(
            model_name='companiongallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
