# Generated by Django 4.2.2 on 2024-06-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_companion_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
